includes:
- https://github.ibm.com/cloud-docs/account
- https://github.ibm.com/cloud-docs/cli
- https://github.ibm.com/cloud-docs/icons
- https://github.ibm.com/cloud-docs/overview
- https://github.ibm.com/cloud-docs/event-notifications